/*
 * generated by Xtext
 */
package org.xtext.example.chess;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ChessRuntimeModule extends org.xtext.example.chess.AbstractChessRuntimeModule {

}
