/*
 * generated by Xtext
 */
package org.xtext.example.chess.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ChessUiModule extends org.xtext.example.chess.ui.AbstractChessUiModule {
	public ChessUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
