/*
 * generated by Xtext
 */
package org.xtext.example.chess.ui.contentassist

import org.xtext.example.chess.ui.contentassist.AbstractChessProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ChessProposalProvider extends AbstractChessProposalProvider {
}
